name: Validate JSON

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Natives JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/natives.json
          INPUT_JSONS: ./natives/natives.json
      - name: Validate Objects JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/objects.json
          INPUT_JSONS: ./objects/objects.json
      - name: Validate Peds JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/objects.json
          INPUT_JSONS: ./objects/peds.json
      - name: Validate Vehicles JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/objects.json
          INPUT_JSONS: ./objects/vehicles.json
      - name: Validate AutoComplete Objects JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./objects/autocomplete/autoobjects.json
      - name: Validate AutoComplete Peds JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./objects/autocomplete/autopeds.json
      - name: Validate AutoComplete Vehicles JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./objects/autocomplete/autovehicles.json
