name: Validate JSON

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Natives JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/natives.json
          INPUT_JSONS: ./natives/natives.json
      - name: Validate Objects JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/objects.json
          INPUT_JSONS: ./objects/objects.json
      - name: Validate Peds JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/objects.json
          INPUT_JSONS: ./objects/peds.json
      - name: Validate Vehicles JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/objects.json
          INPUT_JSONS: ./objects/vehicles.json
      - name: Validate AutoComplete Objects JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./objects/autocomplete/autoobjects.json
      - name: Validate AutoComplete Peds JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./objects/autocomplete/autopeds.json
      - name: Validate AutoComplete Vehicles JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./objects/autocomplete/autovehicles.json
      - name: Validate Filter Peds JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/filters.json
          INPUT_JSONS: ./objects/filters/peds.json
      - name: Validate Filter Objects JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/filters.json
          INPUT_JSONS: ./objects/filters/objects.json
      - name: Validate Filter Natives JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/filters.json
          INPUT_JSONS: ./objects/filters/natives.json
      - name: Validate Filter Vehicles JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/filters.json
          INPUT_JSONS: ./objects/filters/vehicles.json
      - name: Validate Filter Blips JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/filters.json
          INPUT_JSONS: ./blips/filters/blips.json
      - name: Validate Autocomplete Blips JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./blips/autocomplete/blips.json
      - name: Validate Filter Controls JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/filters.json
          INPUT_JSONS: ./controls/filters/controls.json
      - name: Validate Autocomplete Controls JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/autocomplete.json
          INPUT_JSONS: ./controls/autocomplete/controls.json
      - name: Validate Controls JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/blips.json
          INPUT_JSONS: ./blips/blips.json
      - name: Validate Controls JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schemas/controls.json
          INPUT_JSONS: ./controls/controls.json